#SQL to create tables & column setup
TABLE-CREATE: "CREATE TABLE IF NOT EXISTS {table} (
    id TEXT,
    name TEXT,
    url TEXT,
    review_count TEXT,
    categories TEXT,
    rating TEXT,
    price TEXT,
    street TEXT,
    city TEXT,
    zip_code TEXT,
    state TEXT
    );"
#Settings for querying/files/tables
restaurant_locations:
  - query: 'Frankfurt,Germany'
    categories: 'restaurants'
    table: 'frankfurt'
    secondary_index: 'categories'
  - query: 'Berlin,Germany'
    categories: 'restaurants'
    table: 'berlin'
    secondary_index: 'categories'
  - query: 'Munich,Germany'
    categories: 'restaurants'
    table: 'munich'
    secondary_index: 'categories'
  - query: 'Hamburg,Germany'
    categories: 'restaurants'
    table: 'hamburg'
    secondary_index: 'categories'
